const potfolioData = [
  {
    name: "Book Reader",
    caption: "React Native",
    image: "src/assets/images/portfolio/book-reader.gif",
    source_link: "https://github.com/rkpassin132/book_reader_app",
    live_link: "",
    filter_class: "app",
  },
  {
    name: "College Attendance Management",
    caption: "PHP | MySql",
    image: "src/assets/images/portfolio/attendance-management.gif",
    source_link: "https://github.com/rkpassin132/college_attendance_readme",
    live_link: "",
    filter_class: "website",
  },
  {
    name: "SEO plugin",
    caption: "Javascript",
    image: "src/assets/images/portfolio/seo-plugin.jpg",
    source_link: "https://github.com/rkpassin132/seo-plugin",
    live_link: "",
    filter_class: "plugin",
  },
  {
    name: "Destination map",
    caption: "React | Google map API",
    image: "src/assets/images/portfolio/desitnation.png",
    source_link: "https://github.com/rkpassin132/destination-map",
    live_link: "https://rkpassin132-destination-map.netlify.app",
    filter_class: "website",
  },
  {
    name: "Quick WA Chat",
    caption: "Android | Java",
    image: "src/assets/images/portfolio/wa.jpg",
    source_link: "",
    live_link: "https://play.google.com/store/apps/details?id=com.nukepin.quickwachat",
    filter_class: "app",
  },
  {
    name: "UDownload",
    caption: "React | Nodejs",
    image: "src/assets/images/portfolio/udownload.png",
    source_link: "https://github.com/rkpassin132/u-download",
    live_link: "https://udownload.netlify.app/",
    filter_class: "website",
  },
  {
    name: "Mausam",
    caption: "React | Material UI",
    image: "src/assets/images/portfolio/mausam.jpg",
    source_link: "https://github.com/rkpassin132/mausam-kesa",
    live_link: "https://mausam-kaisa.netlify.app/",
    filter_class: "website",
  },
  {
    name: "Promptopia",
    caption: "Next.js | Mongodb",
    image: "src/assets/images/portfolio/promptopia.jpg",
    source_link: "https://github.com/rkpassin132/promptopia",
    live_link: "https://promptopia-here.vercel.app/",
    filter_class: "website",
  },
  {
    name: "Etherscan",
    caption: "Next.js | Ether Api | Infura Api",
    image: "src/assets/images/portfolio/etherscan.jpg",
    source_link: "https://github.com/rkpassin132/etherscan-readme",
    live_link: "https://etherscan-rkpassin132.vercel.app/",
    filter_class: "website",
  },
];
