const potfolioData = [
  {
    name: "Book Reader",
    caption: "React Native",
    image: "src/assets/images/portfolio/book-reader.gif",
    source_link: "https://github.com/rkpassin132/book-reader-app",
    live_link: "",
    filter_class: "app",
  },
  {
    name: "College Attendance Management",
    caption: "PHP | MySql",
    image: "src/assets/images/portfolio/attendance-management.gif",
    source_link: "https://github.com/rkpassin132/college-attendance",
    live_link: "",
    filter_class: "website",
  },
  {
    name: "SEO plugin",
    caption: "Javascript",
    image: "src/assets/images/portfolio/seo-plugin.jpg",
    source_link: "https://github.com/rkpassin132/seo-plugin",
    live_link: "",
    filter_class: "plugin",
  },
  {
    name: "Destination map",
    caption: "React | Google map API",
    image: "src/assets/images/portfolio/desitnation.png",
    source_link: "https://github.com/rkpassin132/destination-map",
    live_link: "https://rkpassin132-destination-map.netlify.app",
    filter_class: "website",
  },
  {
    name: "Quick WA Chat",
    caption: "Android | Java",
    image: "src/assets/images/portfolio/wa.gif",
    source_link: "",
    live_link: "https://play.google.com/store/apps/details?id=com.nukepin.quickwachat",
    filter_class: "app",
  },
];
